INFO:labrad.node:Starting
WARNING:root:Found redundant server configs with same name and version; will use ips_120_10.py. name=ips120_power_supply, version=1.0, conflicting_files=['ips_120_10.py', 'ips_120_10.py']
WARNING:root:Found redundant server configs with same name and version; will use SIM_900.py. name=SIM900, version=1.0.1, conflicting_files=['SIM_900.py', 'SIM_900.py']
WARNING:root:Found redundant server configs with same name and version; will use sr1_server.py. name=SR1, version=0.0.0, conflicting_files=['sr1_server.py', 'sr1_server.py']
WARNING:root:Found redundant server configs with same name and version; will use sr860.py. name=sr860, version=2.7, conflicting_files=['sr860.py', 'sr860.py']
WARNING:root:Found redundant server configs with same name and version; will use sr_760.py. name=Signal Analyzer SR760, version=1.2.1, conflicting_files=['sr_760.py', 'sr_760.py']
WARNING:root:Found redundant server configs with same name and version; will use sr_770.py. name=Signal Analyzer SR770, version=1.2.1, conflicting_files=['sr_770.py', 'sr_770.py']
INFO:labrad.ami_430:STARTING
INFO:labrad.ami_430:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.ami_430:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'ami_430.py']
INFO:labrad.dac_adc_24bits:STARTING
INFO:labrad.dac_adc_24bits:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.dac_adc_24bits:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'dac_adc_24bits.py']
INFO:labrad.data_vault:STARTING
INFO:labrad.data_vault:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.data_vault:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'data_vault.py']
INFO:labrad.he_3_cryostat_gpib_bus:STARTING
INFO:labrad.he_3_cryostat_gpib_bus:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.he_3_cryostat_gpib_bus:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'gpib_server.py']
INFO:labrad.gpib_device_manager:STARTING
INFO:labrad.gpib_device_manager:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.gpib_device_manager:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'gpib_device_manager.py']
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.keithley_2450:STARTING
INFO:labrad.keithley_2450:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.keithley_2450:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'Keithley2450.py']
INFO:labrad.lsci_model350:STARTING
INFO:labrad.lsci_model350:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.lsci_model350:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'lakeshore_370.py']
INFO:labrad.sr830:STARTING
INFO:labrad.sr830:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.sr830:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'SR830.py']
INFO:labrad.he_3_cryostat_serial_server:STARTING
INFO:labrad.he_3_cryostat_serial_server:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.he_3_cryostat_serial_server:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'serial_server.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b'2020-09-20 13:49:34-0700 [LabradProtocol,client] Helium_level_meter starting...'
INFO:labrad.ami_430:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.gpib_device_manager:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.keithley_2450:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.lsci_model350:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.sr830:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:49:34-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b"2020-09-20 13:49:35-0700 [LabradProtocol,client] 'connection failed, disconnecting'"
INFO:labrad.gpib_device_manager:STARTED
INFO:labrad.ami_430:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] AMI 430 starting...'
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] DAC-ADC_24Bits starting...\r\n2020-09-20 13:49:35-0700 [-] loading config info...'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-]  created packet\r\n2020-09-20 13:49:35-0700 [-] printing all the keys ['wine']\r\n2020-09-20 13:49:35-0700 [-] k= wine"
INFO:labrad.gpib_device_manager:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] GPIB Device Manager starting...\r\n2020-09-20 13:49:35-0700 [-] Pinging servers: []\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] GPIB Device Manager now serving'
INFO:labrad.keithley_2450:STARTED
INFO:labrad.sr830:STARTED
INFO:labrad.keithley_2450:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] Keithley_2450 starting...\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] Keithley_2450 now serving'
INFO:labrad.lsci_model350:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] LSCI MODEL350 starting...\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] LSCI MODEL350 now serving'
INFO:labrad.sr830:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] SR830 starting...\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] SR830 now serving'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] he-3-cryostat Serial Server starting...\r\n2020-09-20 13:49:35-0700 [-] Searching for COM ports:\r\n2020-09-20 13:49:35-0700 [-]    COM4\r\n2020-09-20 13:49:35-0700 [-]    COM5'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] he-3-cryostat Serial Server now serving'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-] ans= <labrad.support.PacketResponse object at 0x121ABB50>\r\n2020-09-20 13:49:35-0700 [-] done.\r\n2020-09-20 13:49:35-0700 [-] {'wine': ('he_3_cryostat_serial_server', 'COM4')}"
INFO:labrad.ami_430:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] AMI 430 now serving'
INFO:labrad.helium_level_meter:b'2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:49:35-0700 [-]     result = g.send(result)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 131, in sendRequest\r\n2020-09-20 13:49:35-0700 [-]     returnValue(resp)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:49:35-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:49:35-0700 [-] twisted.internet.defer._DefGen_Return: [(100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None)]\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:49:35-0700 [-]     result = g.send(result)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 174, in send\r\n2020-09-20 13:49:35-0700 [-]     returnValue(PacketResponse(r, self._server, self._packet))\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:49:35-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:49:35-0700 [-] twisted.internet.defer._DefGen_Return: <labrad.support.PacketResponse object at 0x1175C370>\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:49:35-0700 [-]     yield self._initServer()\r\n2020-09-20 13:49:35-0700 [-] KeyError: \'slack_server\'\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] There was an error: \'slack_server\''
INFO:labrad.lsci_model350:STARTED
INFO:labrad.helium_level_meter:b'2020-09-20 13:49:35-0700 [-] Main loop terminated.'
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] DAC-ADC_24Bits now serving'
INFO:labrad.he_3_cryostat_serial_server:STARTED
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:49:35-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:49:35-0700 [-] COM4'
INFO:labrad.ami_430:STARTED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:49:35-0700 [-] connecting to he-3-cryostat Serial Server on port COM4...\r\n2020-09-20 13:49:35-0700 [-]  CONNECTED"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:49:35-0700 [-] Searching for COM ports:\r\n2020-09-20 13:49:35-0700 [-]    COM4\r\n2020-09-20 13:49:35-0700 [-]    COM5\r\n2020-09-20 13:49:35-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:STARTED
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:49:35-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:49:35-0700 [-] COM4'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:49:35-0700 [-] Searching for COM ports:\r\n2020-09-20 13:49:35-0700 [-]    COM4'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:49:35-0700 [-]    COM5'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:49:35-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.he_3_cryostat_gpib_bus:STARTED
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 13:49:35-0700 [-] Log opened.\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] he-3-cryostat GPIB Bus starting...\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] he-3-cryostat GPIB Bus now serving'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:49:35-0700 [-] Searching for COM ports:\r\n2020-09-20 13:49:35-0700 [-]    COM4\r\n2020-09-20 13:49:35-0700 [-]    COM5\r\n2020-09-20 13:49:35-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:49:35-0700 [-] COM4\r\n2020-09-20 13:49:35-0700 [-] ['COM4', 'COM5']"
INFO:labrad.data_vault:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] Log opened.'
INFO:labrad.data_vault:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] Data Vault starting...'
INFO:labrad.data_vault:b'2020-09-20 13:49:35-0700 [LabradProtocol,client] Data Vault now serving'
INFO:labrad.data_vault:STARTED
ERROR:root:Failed to autostart "Helium_level_meter"
Traceback (most recent call last):
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\labrad\protocol.py", line 131, in sendRequest
    returnValue(resp)
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [(60, None)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\labrad\wrappers.py", line 60, in __call__
    returnValue(r[0][1])
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\feldman lab\appdata\local\programs\python\python37-32\lib\site-packages\labrad\node\__init__.py", line 817, in autostart
    yield deferred
labrad.types.types.Error: (0) Process exited before connecting to labrad. [payload=[(datetime.datetime(2020, 9, 20, 13, 49, 34, 919409), b'2020-09-20 13:49:34-0700 [-] Log opened.\r\n'), (datetime.datetime(2020, 9, 20, 13, 49, 34, 994210), b'2020-09-20 13:49:34-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n'), (datetime.datetime(2020, 9, 20, 13, 49, 35, 113889), b"2020-09-20 13:49:35-0700 [LabradProtocol,client] 'connection failed, disconnecting'\r\n"), (datetime.datetime(2020, 9, 20, 13, 49, 35, 205643), b'2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:49:35-0700 [-]     result = g.send(result)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 131, in sendRequest\r\n2020-09-20 13:49:35-0700 [-]     returnValue(resp)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:49:35-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:49:35-0700 [-] twisted.internet.defer._DefGen_Return: [(100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None)]\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:49:35-0700 [-]     result = g.send(result)\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 174, in send\r\n2020-09-20 13:49:35-0700 [-]     returnValue(PacketResponse(r, self._server, self._packet))\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:49:35-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:49:35-0700 [-] twisted.internet.defer._DefGen_Return: <labrad.support.PacketResponse object at 0x1175C370>\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:49:35-0700 [-] \r\n2020-09-20 13:49:35-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:49:35-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:49:35-0700 [-]     yield self._initServer()\r\n2020-09-20 13:49:35-0700 [-] KeyError: \'slack_server\'\r\n2020-09-20 13:49:35-0700 [LabradProtocol,client] There was an error: \'slack_server\'\r\n'), (datetime.datetime(2020, 9, 20, 13, 49, 35, 209634), b'2020-09-20 13:49:35-0700 [-] Main loop terminated.\r\n')]]
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:49:35-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:49:35-0700 [-] COM4\r\n2020-09-20 13:49:35-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:49:35-0700 [-] Searching for COM ports:\r\n2020-09-20 13:49:35-0700 [-]    COM4\r\n2020-09-20 13:49:35-0700 [-]    COM5\r\n2020-09-20 13:49:35-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 13:49:35-0700 [-] GPIB Device Connect: TCPIP0::169.254.193.6::7180::SOCKET'
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 13:49:37-0700 [-] Failed to add TCPIP0::169.254.129.190::7180::SOCKET:VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.\r\n2020-09-20 13:49:37-0700 [-] GPIB Device Connect: GPIB0::8::INSTR\r\n2020-09-20 13:49:37-0700 [-] GPIB Device Connect: GPIB0::1::INSTR'
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 13:49:39-0700 [-] Failed to add TCPIP0::169.254.246.230::7180::SOCKET:VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.\r\n2020-09-20 13:49:40-0700 [-] GPIB Device Connect: GPIB0::21::INSTR'
INFO:labrad.gpib_device_manager:b'2020-09-20 13:49:40-0700 [-] Device Connect: he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 13:49:40-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 13:49:40-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 13:49:40-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 13:49:40-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::21::INSTR'
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:50:47-0700 [-] Log opened.\r\n2020-09-20 13:50:47-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:50:47-0700 [LabradProtocol,client] \'connection failed, disconnecting\'\r\n2020-09-20 13:50:47-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:50:47-0700 [-]     result = g.send(result)\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 131, in sendRequest\r\n2020-09-20 13:50:47-0700 [-]     returnValue(resp)\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:50:47-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:50:47-0700 [-] twisted.internet.defer._DefGen_Return: [(100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None), (100, None)]\r\n2020-09-20 13:50:47-0700 [-] \r\n2020-09-20 13:50:47-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:50:47-0700 [-] \r\n2020-09-20 13:50:47-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1418, in _inlineCallbacks\r\n2020-09-20 13:50:47-0700 [-]     result = g.send(result)\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 174, in send\r\n2020-09-20 13:50:47-0700 [-]     returnValue(PacketResponse(r, self._server, self._packet))\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\twisted\\internet\\defer.py", line 1362, in returnValue\r\n2020-09-20 13:50:47-0700 [-]     raise _DefGen_Return(val)\r\n2020-09-20 13:50:47-0700 [-] twisted.internet.defer._DefGen_Return: <labrad.support.PacketResponse object at 0x116C31F0>\r\n2020-09-20 13:50:47-0700 [-] \r\n2020-09-20 13:50:47-0700 [-] During handling of the above exception, another exception occurred:\r\n2020-09-20 13:50:47-0700 [-] \r\n2020-09-20 13:50:47-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:50:47-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:50:47-0700 [-]     yield self._initServer()\r\n2020-09-20 13:50:47-0700 [-] KeyError: \'slack_server\'\r\n2020-09-20 13:50:47-0700 [LabradProtocol,client] There was an error: \'slack_server\'\r\n2020-09-20 13:50:47-0700 [-] Main loop terminated.'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:50:47-0700 [-] Searching for COM ports:\r\n2020-09-20 13:50:47-0700 [-]    COM4\r\n2020-09-20 13:50:47-0700 [-]    COM5\r\n2020-09-20 13:50:47-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:50:47-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:50:47-0700 [-] COM4\r\n2020-09-20 13:50:47-0700 [-] ['COM4', 'COM5']"
WARNING:root:Found redundant server configs with same name and version; will use ips_120_10.py. name=ips120_power_supply, version=1.0, conflicting_files=['ips_120_10.py', 'ips_120_10.py']
WARNING:root:Found redundant server configs with same name and version; will use SIM_900.py. name=SIM900, version=1.0.1, conflicting_files=['SIM_900.py', 'SIM_900.py']
WARNING:root:Found redundant server configs with same name and version; will use sr1_server.py. name=SR1, version=0.0.0, conflicting_files=['sr1_server.py', 'sr1_server.py']
WARNING:root:Found redundant server configs with same name and version; will use sr860.py. name=sr860, version=2.7, conflicting_files=['sr860.py', 'sr860.py']
WARNING:root:Found redundant server configs with same name and version; will use sr_760.py. name=Signal Analyzer SR760, version=1.2.1, conflicting_files=['sr_760.py', 'sr_760.py']
WARNING:root:Found redundant server configs with same name and version; will use sr_770.py. name=Signal Analyzer SR770, version=1.2.1, conflicting_files=['sr_770.py', 'sr_770.py']
INFO:labrad.slack_server:STARTING
INFO:labrad.slack_server:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.slack_server:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'slack_server.py']
INFO:labrad.slack_server:b'2020-09-20 13:50:59-0700 [-] Log opened.'
INFO:labrad.slack_server:b'2020-09-20 13:50:59-0700 [LabradProtocol,client] Slack Server starting...\r\n2020-09-20 13:50:59-0700 [LabradProtocol,client] Slack Server now serving'
INFO:labrad.slack_server:STARTED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:50:59-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:50:59-0700 [-] COM4\r\n2020-09-20 13:50:59-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:50:59-0700 [-] Searching for COM ports:\r\n2020-09-20 13:50:59-0700 [-]    COM4\r\n2020-09-20 13:50:59-0700 [-]    COM5\r\n2020-09-20 13:50:59-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:02-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b"2020-09-20 13:51:02-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:51:02-0700 [-] loading config info...\r\n2020-09-20 13:51:02-0700 [-]  created packet\r\n2020-09-20 13:51:02-0700 [-] printing all the keys ['ami_cryostat']\r\n2020-09-20 13:51:02-0700 [-] k= ami_cryostat\r\n2020-09-20 13:51:02-0700 [-] ans= <labrad.support.PacketResponse object at 0x1172A870>\r\n2020-09-20 13:51:02-0700 [-] done.\r\n2020-09-20 13:51:02-0700 [-] {'ami_cryostat': ('he_3_cryostat_serial_server', 'COM5', 'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4')}\r\n2020-09-20 13:51:02-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x116FD850>\r\n2020-09-20 13:51:02-0700 [-] COM5\r\n2020-09-20 13:51:02-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:51:02-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:51:02-0700 [-]  CONNECTED"
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:02-0700 [LabradProtocol,client] \'connection failed, disconnecting\'\r\n2020-09-20 13:51:02-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:51:02-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:51:02-0700 [-]     yield self._initServer()\r\n2020-09-20 13:51:02-0700 [-] labrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n2020-09-20 13:51:02-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n2020-09-20 13:51:02-0700 [-]     result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n2020-09-20 13:51:02-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n2020-09-20 13:51:02-0700 [-]     return func(*args, **kw)\r\n2020-09-20 13:51:02-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n2020-09-20 13:51:02-0700 [-]     return self.func(server, c, data)\r\n2020-09-20 13:51:02-0700 [-]   File "serial_server.py", line 193, in open\r\n2020-09-20 13:51:02-0700 [-]     raise Error(code=2, msg=message)\r\n2020-09-20 13:51:02-0700 [-] labrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n2020-09-20 13:51:02-0700 [-]  [payload=None]\r\n2020-09-20 13:51:02-0700 [LabradProtocol,client] There was an error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]\r\n2020-09-20 13:51:02-0700 [-] Main loop terminated.'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:51:02-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:02-0700 [-]    COM4\r\n2020-09-20 13:51:02-0700 [-]    COM5\r\n2020-09-20 13:51:02-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:51:02-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:02-0700 [-]    COM4\r\n2020-09-20 13:51:02-0700 [-]    COM5\r\n2020-09-20 13:51:02-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:51:02-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:51:02-0700 [-] COM4\r\n2020-09-20 13:51:02-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:05-0700 [-] Log opened.'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:51:05-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:51:05-0700 [-] COM4\r\n2020-09-20 13:51:05-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:51:05-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:05-0700 [-]    COM4\r\n2020-09-20 13:51:05-0700 [-]    COM5\r\n2020-09-20 13:51:05-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:51:05-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:05-0700 [-]    COM4\r\n2020-09-20 13:51:05-0700 [-]    COM5\r\n2020-09-20 13:51:05-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:05-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:51:05-0700 [-] loading config info...\r\n2020-09-20 13:51:05-0700 [-]  created packet\r\n2020-09-20 13:51:05-0700 [-] printing all the keys [\'ami_cryostat\']\r\n2020-09-20 13:51:05-0700 [-] k= ami_cryostat\r\n2020-09-20 13:51:05-0700 [-] ans= <labrad.support.PacketResponse object at 0x11EB90F0>\r\n2020-09-20 13:51:05-0700 [-] done.\r\n2020-09-20 13:51:05-0700 [-] {\'ami_cryostat\': (\'he_3_cryostat_serial_server\', \'COM5\', \'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4\')}\r\n2020-09-20 13:51:05-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11E8F810>\r\n2020-09-20 13:51:05-0700 [-] COM5\r\n2020-09-20 13:51:05-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:51:05-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:51:05-0700 [-]  CONNECTED \r\n2020-09-20 13:51:05-0700 [LabradProtocol,client] \'connection failed, disconnecting\'\r\n2020-09-20 13:51:05-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:51:05-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:51:05-0700 [-]     yield self._initServer()\r\n2020-09-20 13:51:05-0700 [-] labrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n2020-09-20 13:51:05-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n2020-09-20 13:51:05-0700 [-]     result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n2020-09-20 13:51:05-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n2020-09-20 13:51:05-0700 [-]     return func(*args, **kw)\r\n2020-09-20 13:51:05-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n2020-09-20 13:51:05-0700 [-]     return self.func(server, c, data)\r\n2020-09-20 13:51:05-0700 [-]   File "serial_server.py", line 193, in open\r\n2020-09-20 13:51:05-0700 [-]     raise Error(code=2, msg=message)\r\n2020-09-20 13:51:05-0700 [-] labrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n2020-09-20 13:51:05-0700 [-]  [payload=None]\r\n2020-09-20 13:51:05-0700 [LabradProtocol,client] There was an error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]\r\n2020-09-20 13:51:05-0700 [-] Main loop terminated.'
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.he_3_cryostat_serial_server:STOPPING
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:12-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:51:12-0700 [-] Main loop terminated.'
INFO:labrad.he_3_cryostat_serial_server:process closed cleanly.
INFO:labrad.he_3_cryostat_serial_server:STOPPED
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:15-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b"2020-09-20 13:51:15-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:51:15-0700 [-] loading config info...\r\n2020-09-20 13:51:15-0700 [-]  created packet\r\n2020-09-20 13:51:15-0700 [-] printing all the keys ['ami_cryostat']\r\n2020-09-20 13:51:15-0700 [-] k= ami_cryostat"
INFO:labrad.helium_level_meter:b"2020-09-20 13:51:15-0700 [-] ans= <labrad.support.PacketResponse object at 0x11F9F610>\r\n2020-09-20 13:51:15-0700 [-] done.\r\n2020-09-20 13:51:15-0700 [-] {'ami_cryostat': ('he_3_cryostat_serial_server', 'COM5', 'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4')}"
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:15-0700 [LabradProtocol,client] Helium_level_meter now serving'
INFO:labrad.helium_level_meter:STARTED
INFO:labrad.he_3_cryostat_serial_server:STARTING
INFO:labrad.he_3_cryostat_serial_server:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.he_3_cryostat_serial_server:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'serial_server.py']
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:18-0700 [-] Log opened.'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:18-0700 [LabradProtocol,client] he-3-cryostat Serial Server starting...\r\n2020-09-20 13:51:18-0700 [-] Searching for COM ports:'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:18-0700 [-]    COM4'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:18-0700 [-]    COM5'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:18-0700 [LabradProtocol,client] he-3-cryostat Serial Server now serving'
INFO:labrad.he_3_cryostat_serial_server:STARTED
INFO:labrad.ami_430:STOPPING
INFO:labrad.dac_adc_24bits:b'2020-09-20 13:51:29-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:51:29-0700 [-] COM4'
INFO:labrad.ami_430:b'2020-09-20 13:51:29-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:51:29-0700 [-] Main loop terminated.'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:51:29-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:51:29-0700 [-] connecting to he-3-cryostat Serial Server on port COM4...\r\n2020-09-20 13:51:29-0700 [-]  CONNECTED"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:51:29-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:29-0700 [-]    COM4\r\n2020-09-20 13:51:29-0700 [-]    COM5\r\n2020-09-20 13:51:29-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:51:29-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:29-0700 [-]    COM4\r\n2020-09-20 13:51:29-0700 [-]    COM5\r\n2020-09-20 13:51:29-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.ami_430:process closed cleanly.
INFO:labrad.ami_430:STOPPED
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:29-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:51:29-0700 [-] COM5\r\n2020-09-20 13:51:29-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:51:29-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:51:29-0700 [-]  CONNECTED \r\n2020-09-20 13:51:29-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:51:29-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.ami_430:STARTING
INFO:labrad.ami_430:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.ami_430:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'ami_430.py']
INFO:labrad.ami_430:b'2020-09-20 13:51:30-0700 [-] Log opened.'
INFO:labrad.ami_430:b'2020-09-20 13:51:30-0700 [LabradProtocol,client] AMI 430 starting...'
INFO:labrad.ami_430:b'2020-09-20 13:51:30-0700 [-] Device message: AMERICAN MAGNETICS INC. MODEL 430 he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET True'
INFO:labrad.ami_430:STARTED
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:30-0700 [-] Searching for COM ports:\r\n2020-09-20 13:51:30-0700 [-]    COM4'
INFO:labrad.ami_430:b'2020-09-20 13:51:30-0700 [LabradProtocol,client] AMI 430 now serving'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:30-0700 [-]    COM5'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:51:30-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:51:30-0700 [-] Searching for COM ports:"
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:51:30-0700 [-]    COM4'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:51:30-0700 [-]    COM5\r\n2020-09-20 13:51:30-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:51:30-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:51:30-0700 [-] COM4\r\n2020-09-20 13:51:30-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:b'2020-09-20 13:51:30-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:51:30-0700 [-] COM5\r\n2020-09-20 13:51:30-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:51:30-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:51:30-0700 [-]  CONNECTED \r\n2020-09-20 13:51:30-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:51:30-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.lsci_model350:STOPPING
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:08-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:52:08-0700 [-] COM5'
INFO:labrad.helium_level_meter:b"2020-09-20 13:52:08-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:52:08-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:52:08-0700 [-]  CONNECTED"
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:08-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:52:08-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:08-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:52:08-0700 [-] Main loop terminated.'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:08-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:08-0700 [-] COM4\r\n2020-09-20 13:52:08-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:08-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:08-0700 [-]    COM4\r\n2020-09-20 13:52:08-0700 [-]    COM5\r\n2020-09-20 13:52:08-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:52:08-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:08-0700 [-]    COM4\r\n2020-09-20 13:52:08-0700 [-]    COM5\r\n2020-09-20 13:52:08-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.lsci_model350:process closed cleanly.
INFO:labrad.lsci_model350:STOPPED
INFO:labrad.lsci_model350:STARTING
INFO:labrad.lsci_model350:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.lsci_model350:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'lakeshore_370.py']
INFO:labrad.lsci_model350:b'2020-09-20 13:52:09-0700 [-] Log opened.'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:09-0700 [LabradProtocol,client] LSCI MODEL350 starting...'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:09-0700 [-] Device message: LSCI MODEL350 he-3-cryostat GPIB Bus GPIB0::21::INSTR True'
INFO:labrad.lsci_model350:STARTED
INFO:labrad.lsci_model350:b'2020-09-20 13:52:09-0700 [LabradProtocol,client] LSCI MODEL350 now serving'
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:09-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:09-0700 [-] COM4\r\n2020-09-20 13:52:09-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:09-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:52:09-0700 [-] COM5\r\n2020-09-20 13:52:09-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:52:09-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:52:09-0700 [-]  CONNECTED \r\n2020-09-20 13:52:09-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:52:09-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:09-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:09-0700 [-]    COM4\r\n2020-09-20 13:52:09-0700 [-]    COM5\r\n2020-09-20 13:52:09-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:52:09-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:09-0700 [-]    COM4\r\n2020-09-20 13:52:09-0700 [-]    COM5\r\n2020-09-20 13:52:09-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.lsci_model350:STOPPING
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:21-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:21-0700 [-]    COM4\r\n2020-09-20 13:52:21-0700 [-]    COM5\r\n2020-09-20 13:52:21-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:52:21-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:21-0700 [-]    COM4\r\n2020-09-20 13:52:21-0700 [-]    COM5\r\n2020-09-20 13:52:21-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:21-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:21-0700 [-] COM4\r\n2020-09-20 13:52:21-0700 [-] ['COM4', 'COM5']"
INFO:labrad.gpib_device_manager:b'2020-09-20 13:52:21-0700 [-] Expiring context: (11, 0)'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:21-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:52:21-0700 [-] Main loop terminated.'
INFO:labrad.lsci_model350:process closed cleanly.
INFO:labrad.lsci_model350:STOPPED
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:21-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:52:21-0700 [-] COM5\r\n2020-09-20 13:52:21-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:52:21-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:52:21-0700 [-]  CONNECTED \r\n2020-09-20 13:52:21-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:52:21-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.lsci_model350:STARTING
INFO:labrad.lsci_model350:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.lsci_model350:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'lakeshore_370.py']
INFO:labrad.lsci_model350:b'2020-09-20 13:52:22-0700 [-] Log opened.\r\n2020-09-20 13:52:22-0700 [LabradProtocol,client] LSCI MODEL350 starting...'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:22-0700 [-] Device message: LSCI MODEL350 he-3-cryostat GPIB Bus GPIB0::21::INSTR True'
INFO:labrad.lsci_model350:b'2020-09-20 13:52:22-0700 [LabradProtocol,client] LSCI MODEL350 now serving'
INFO:labrad.lsci_model350:STARTED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:22-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:22-0700 [-] COM4\r\n2020-09-20 13:52:22-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:22-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11FA5ED0>\r\n2020-09-20 13:52:22-0700 [-] COM5\r\n2020-09-20 13:52:22-0700 [-] [\'COM4\', \'COM5\']\r\n2020-09-20 13:52:22-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:52:22-0700 [-]  CONNECTED \r\n2020-09-20 13:52:22-0700 [-] Unhandled error in Deferred:\r\n2020-09-20 13:52:22-0700 [-] Unhandled Error\r\n\tTraceback (most recent call last):\r\n\t--- <exception caught here> ---\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\devices.py", line 185, in _doRefresh\r\n\t    yield dev.connect(*args, **kw)\r\n\t  File "he_level_meter.py", line 67, in connect\r\n\t    yield p.send()\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\wrappers.py", line 173, in send\r\n\t    r = yield self._server._send(records, **dict(self._kw, **kw))\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\protocol.py", line 130, in sendRequest\r\n\t    resp = yield self._sendRequestNoLookup(target, records, context, timeout, unflatten)\r\n\tlabrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:22-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:22-0700 [-]    COM4\r\n2020-09-20 13:52:22-0700 [-]    COM5\r\n2020-09-20 13:52:22-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:52:22-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:22-0700 [-]    COM4\r\n2020-09-20 13:52:22-0700 [-]    COM5\r\n2020-09-20 13:52:22-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:STOPPING
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:26-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:26-0700 [-]    COM4\r\n2020-09-20 13:52:26-0700 [-]    COM5\r\n2020-09-20 13:52:26-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:26-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:26-0700 [-] COM4\r\n2020-09-20 13:52:26-0700 [-] ['COM4', 'COM5']"
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:26-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:52:26-0700 [-] Main loop terminated.'
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:27-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b"2020-09-20 13:52:27-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:52:27-0700 [-] loading config info...\r\n2020-09-20 13:52:27-0700 [-]  created packet\r\n2020-09-20 13:52:27-0700 [-] printing all the keys ['ami_cryostat']\r\n2020-09-20 13:52:27-0700 [-] k= ami_cryostat"
INFO:labrad.helium_level_meter:b"2020-09-20 13:52:27-0700 [-] ans= <labrad.support.PacketResponse object at 0x11DD98D0>\r\n2020-09-20 13:52:27-0700 [-] done.\r\n2020-09-20 13:52:27-0700 [-] {'ami_cryostat': ('he_3_cryostat_serial_server', 'COM5', 'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4')}\r\n2020-09-20 13:52:27-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x11DAE7F0>\r\n2020-09-20 13:52:27-0700 [-] COM5"
INFO:labrad.helium_level_meter:b"2020-09-20 13:52:27-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:52:27-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:52:27-0700 [-]  CONNECTED"
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:27-0700 [LabradProtocol,client] \'connection failed, disconnecting\'\r\n2020-09-20 13:52:27-0700 [-] Traceback (most recent call last):\r\n2020-09-20 13:52:27-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 361, in startup\r\n2020-09-20 13:52:27-0700 [-]     yield self._initServer()\r\n2020-09-20 13:52:27-0700 [-] labrad.types.types.Error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n2020-09-20 13:52:27-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n2020-09-20 13:52:27-0700 [-]     result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n2020-09-20 13:52:27-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n2020-09-20 13:52:27-0700 [-]     return func(*args, **kw)\r\n2020-09-20 13:52:27-0700 [-]   File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest'
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:27-0700 [-]     return self.func(server, c, data)\r\n2020-09-20 13:52:27-0700 [-]   File "serial_server.py", line 193, in open\r\n2020-09-20 13:52:27-0700 [-]     raise Error(code=2, msg=message)\r\n2020-09-20 13:52:27-0700 [-] labrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n2020-09-20 13:52:27-0700 [-]  [payload=None]'
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:27-0700 [LabradProtocol,client] There was an error: (2) [he-3-cryostat Serial Server] Remote Traceback (most recent call last):\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 246, in request_handler\r\n\t    result = yield self._dispatch(setting.handleRequest, self, c.data, flat_data)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\server.py", line 212, in _dispatch\r\n\t    return func(*args, **kw)\r\n\t  File "c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\labrad\\decorators.py", line 184, in handleRequest\r\n\t    return self.func(server, c, data)\r\n\t  File "serial_server.py", line 193, in open\r\n\t    raise Error(code=2, msg=message)\r\n\tlabrad.types.types.Error: (2) Cannot configure port, something went wrong. Original message: PermissionError(13, \'A device attached to the system is not functioning.\', None, 31) [payload=None]\r\n\t [payload=None]'
INFO:labrad.helium_level_meter:b'2020-09-20 13:52:27-0700 [-] Main loop terminated.'
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:52:27-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:52:27-0700 [-] COM4\r\n2020-09-20 13:52:27-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:52:27-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:27-0700 [-]    COM4\r\n2020-09-20 13:52:27-0700 [-]    COM5\r\n2020-09-20 13:52:27-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:52:27-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:27-0700 [-]    COM4\r\n2020-09-20 13:52:27-0700 [-]    COM5\r\n2020-09-20 13:52:27-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.he_3_cryostat_serial_server:STOPPING
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:52:34-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:52:34-0700 [-] Main loop terminated.'
INFO:labrad.he_3_cryostat_serial_server:process closed cleanly.
INFO:labrad.he_3_cryostat_serial_server:STOPPED
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:STARTED
INFO:labrad.helium_level_meter:b"2020-09-20 13:52:37-0700 [-] Log opened.\r\n2020-09-20 13:52:37-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:52:37-0700 [-] loading config info...\r\n2020-09-20 13:52:37-0700 [-]  created packet\r\n2020-09-20 13:52:37-0700 [-] printing all the keys ['ami_cryostat']\r\n2020-09-20 13:52:37-0700 [-] k= ami_cryostat\r\n2020-09-20 13:52:37-0700 [-] ans= <labrad.support.PacketResponse object at 0x118AFDF0>\r\n2020-09-20 13:52:37-0700 [-] done.\r\n2020-09-20 13:52:37-0700 [-] {'ami_cryostat': ('he_3_cryostat_serial_server', 'COM5', 'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4')}\r\n2020-09-20 13:52:37-0700 [LabradProtocol,client] Helium_level_meter now serving"
INFO:labrad.he_3_cryostat_serial_server:STARTING
INFO:labrad.he_3_cryostat_serial_server:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.he_3_cryostat_serial_server:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'serial_server.py']
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:52:40-0700 [-] Log opened.'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:52:40-0700 [LabradProtocol,client] he-3-cryostat Serial Server starting...\r\n2020-09-20 13:52:40-0700 [-] Searching for COM ports:\r\n2020-09-20 13:52:40-0700 [-]    COM4\r\n2020-09-20 13:52:40-0700 [-]    COM5'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 13:52:40-0700 [LabradProtocol,client] he-3-cryostat Serial Server now serving'
INFO:labrad.he_3_cryostat_serial_server:STARTED
INFO:labrad.helium_level_meter:STOPPING
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:55:28-0700 [-] Searching for COM ports:\r\n2020-09-20 13:55:28-0700 [-]    COM4\r\n2020-09-20 13:55:28-0700 [-]    COM5\r\n2020-09-20 13:55:28-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:b'2020-09-20 13:55:28-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 13:55:28-0700 [-] Main loop terminated.'
INFO:labrad.helium_level_meter:process closed cleanly.
INFO:labrad.helium_level_meter:STOPPED
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:55:28-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:55:28-0700 [-] COM4\r\n2020-09-20 13:55:28-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:55:28-0700 [-] connecting to he-3-cryostat Serial Server on port COM4...\r\n2020-09-20 13:55:28-0700 [-]  CONNECTED"
INFO:labrad.helium_level_meter:STARTING
INFO:labrad.helium_level_meter:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.helium_level_meter:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'he_level_meter.py']
INFO:labrad.helium_level_meter:b'2020-09-20 13:55:29-0700 [-] Log opened.'
INFO:labrad.helium_level_meter:b"2020-09-20 13:55:29-0700 [LabradProtocol,client] Helium_level_meter starting...\r\n2020-09-20 13:55:29-0700 [-] loading config info...\r\n2020-09-20 13:55:29-0700 [-]  created packet\r\n2020-09-20 13:55:29-0700 [-] printing all the keys ['ami_cryostat']\r\n2020-09-20 13:55:29-0700 [-] k= ami_cryostat\r\n2020-09-20 13:55:29-0700 [-] ans= <labrad.support.PacketResponse object at 0x1166A430>\r\n2020-09-20 13:55:29-0700 [-] done.\r\n2020-09-20 13:55:29-0700 [-] {'ami_cryostat': ('he_3_cryostat_serial_server', 'COM5', 'xoxb-542804265300-1280091538838-tPDDiMD7kG6mxS2h1f71rTP4')}\r\n2020-09-20 13:55:29-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 13:55:29-0700 [-] COM5\r\n2020-09-20 13:55:29-0700 [-] ['COM4', 'COM5']\r\n2020-09-20 13:55:29-0700 [-] connecting to he-3-cryostat Serial Server on port COM5...\r\n2020-09-20 13:55:29-0700 [-]  CONNECTED \r\n2020-09-20 13:55:29-0700 [-]  SLACK BOT CONNECTED"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:55:29-0700 [-] Searching for COM ports:\r\n2020-09-20 13:55:29-0700 [-]    COM4\r\n2020-09-20 13:55:29-0700 [-]    COM5\r\n2020-09-20 13:55:29-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.helium_level_meter:b'2020-09-20 13:55:30-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 13:55:30-0700 [-] COM5'
INFO:labrad.helium_level_meter:b'2020-09-20 13:55:30-0700 [LabradProtocol,client] Helium_level_meter now serving'
INFO:labrad.helium_level_meter:STARTED
INFO:labrad.helium_level_meter:b"2020-09-20 13:55:30-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 13:55:30-0700 [-] Searching for COM ports:\r\n2020-09-20 13:55:30-0700 [-]    COM4\r\n2020-09-20 13:55:30-0700 [-]    COM5\r\n2020-09-20 13:55:30-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 13:55:30-0700 [-] Searching for COM ports:\r\n2020-09-20 13:55:30-0700 [-]    COM4\r\n2020-09-20 13:55:30-0700 [-]    COM5\r\n2020-09-20 13:55:30-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.dac_adc_24bits:b"2020-09-20 13:55:30-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 13:55:30-0700 [-] COM4\r\n2020-09-20 13:55:30-0700 [-] ['COM4', 'COM5']"
INFO:labrad.sr830:STOPPING
INFO:labrad.helium_level_meter:b"2020-09-20 21:27:58-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 21:27:58-0700 [-] COM5\r\n2020-09-20 21:27:58-0700 [-] ['COM4', 'COM5']"
INFO:labrad.sr830:b'2020-09-20 21:27:58-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 21:27:58-0700 [-] Main loop terminated.'
INFO:labrad.dac_adc_24bits:b"2020-09-20 21:27:58-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 21:27:58-0700 [-] COM4\r\n2020-09-20 21:27:58-0700 [-] ['COM4', 'COM5']"
INFO:labrad.sr830:process closed cleanly.
INFO:labrad.sr830:STOPPED
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 21:27:58-0700 [-] Searching for COM ports:\r\n2020-09-20 21:27:58-0700 [-]    COM4\r\n2020-09-20 21:27:58-0700 [-]    COM5\r\n2020-09-20 21:27:58-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 21:27:58-0700 [-] Searching for COM ports:\r\n2020-09-20 21:27:58-0700 [-]    COM4\r\n2020-09-20 21:27:58-0700 [-]    COM5\r\n2020-09-20 21:27:58-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.sr830:STARTING
INFO:labrad.sr830:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.sr830:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'SR830.py']
INFO:labrad.sr830:b'2020-09-20 21:28:01-0700 [-] Log opened.\r\n2020-09-20 21:28:01-0700 [LabradProtocol,client] SR830 starting...'
INFO:labrad.sr830:b'2020-09-20 21:28:01-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::8::INSTR True\r\n2020-09-20 21:28:01-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::1::INSTR True'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 21:28:01-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:01-0700 [-]    COM4\r\n2020-09-20 21:28:01-0700 [-]    COM5\r\n2020-09-20 21:28:01-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 21:28:01-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:01-0700 [-]    COM4\r\n2020-09-20 21:28:01-0700 [-]    COM5\r\n2020-09-20 21:28:01-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.sr830:STARTED
INFO:labrad.sr830:b'2020-09-20 21:28:01-0700 [LabradProtocol,client] SR830 now serving'
INFO:labrad.helium_level_meter:b"2020-09-20 21:28:01-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 21:28:01-0700 [-] COM5\r\n2020-09-20 21:28:01-0700 [-] ['COM4', 'COM5']"
INFO:labrad.dac_adc_24bits:b"2020-09-20 21:28:01-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 21:28:01-0700 [-] COM4\r\n2020-09-20 21:28:01-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_gpib_bus:STOPPING
INFO:labrad.lsci_model350:b'2020-09-20 21:28:02-0700 [-] Device message: LSCI MODEL350 he-3-cryostat GPIB Bus GPIB0::21::INSTR False'
INFO:labrad.ami_430:b'2020-09-20 21:28:02-0700 [-] Device message: AMERICAN MAGNETICS INC. MODEL 430 he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET False'
INFO:labrad.helium_level_meter:b"2020-09-20 21:28:02-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 21:28:02-0700 [-] COM5\r\n2020-09-20 21:28:02-0700 [-] ['COM4', 'COM5']"
INFO:labrad.dac_adc_24bits:b"2020-09-20 21:28:02-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 21:28:02-0700 [-] COM4\r\n2020-09-20 21:28:02-0700 [-] ['COM4', 'COM5']"
INFO:labrad.sr830:b'2020-09-20 21:28:02-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::8::INSTR False\r\n2020-09-20 21:28:02-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::1::INSTR False'
INFO:labrad.gpib_device_manager:b"2020-09-20 21:28:02-0700 [-] Device Disconnect: he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 21:28:02-0700 [-] Sending message: 9 (9, 0) [(21436587, ('AMERICAN MAGNETICS INC. MODEL 430', 'he-3-cryostat GPIB Bus', 'TCPIP0::169.254.193.6::7180::SOCKET', False))]\r\n2020-09-20 21:28:02-0700 [-] Device Disconnect: he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 21:28:02-0700 [-] Sending message: 10 (10, 0) [(21436587, ('Stanford_Research_Systems SR830', 'he-3-cryostat GPIB Bus', 'GPIB0::8::INSTR', False))]\r\n2020-09-20 21:28:02-0700 [-] Device Disconnect: he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 21:28:02-0700 [-] Sending message: 10 (10, 0) [(21436587, ('Stanford_Research_Systems SR830', 'he-3-cryostat GPIB Bus', 'GPIB0::1::INSTR', False))]\r\n2020-09-20 21:28:02-0700 [-] Device Disconnect: he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 21:28:02-0700 [-] Sending message: 11 (11, 0) [(21436587, ('LSCI MODEL350', 'he-3-cryostat GPIB Bus', 'GPIB0::21::INSTR', False))]"
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:02-0700 [LabradProtocol,client] Disconnected cleanly.\r\n2020-09-20 21:28:02-0700 [-] Main loop terminated.'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 21:28:02-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:02-0700 [-]    COM4\r\n2020-09-20 21:28:02-0700 [-]    COM5\r\n2020-09-20 21:28:02-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 21:28:02-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:02-0700 [-]    COM4\r\n2020-09-20 21:28:02-0700 [-]    COM5\r\n2020-09-20 21:28:02-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.he_3_cryostat_gpib_bus:process closed cleanly.
INFO:labrad.he_3_cryostat_gpib_bus:STOPPED
INFO:labrad.he_3_cryostat_gpib_bus:STARTING
INFO:labrad.he_3_cryostat_gpib_bus:path: C:/Users/Feldman Lab/code/github/feldmanlab/LabRAD-Device-Electrical_Measurement-ONline_Software/DEMONS Servers
INFO:labrad.he_3_cryostat_gpib_bus:args: ['c:\\users\\feldman lab\\appdata\\local\\programs\\python\\python37-32\\python.exe', 'gpib_server.py']
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:03-0700 [-] Log opened.'
INFO:labrad.he_3_cryostat_serial_server:b"2020-09-20 21:28:04-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:04-0700 [-]    COM4\r\n2020-09-20 21:28:04-0700 [-]    COM5\r\n2020-09-20 21:28:04-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]\r\n2020-09-20 21:28:04-0700 [-] Searching for COM ports:\r\n2020-09-20 21:28:04-0700 [-]    COM4\r\n2020-09-20 21:28:04-0700 [-]    COM5\r\n2020-09-20 21:28:04-0700 [-] [SerialDevice(name='COM4', devicepath='\\\\\\\\.\\\\COM4'), SerialDevice(name='COM5', devicepath='\\\\\\\\.\\\\COM5')]"
INFO:labrad.he_3_cryostat_gpib_bus:STARTED
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:04-0700 [LabradProtocol,client] he-3-cryostat GPIB Bus starting...\r\n2020-09-20 21:28:04-0700 [LabradProtocol,client] he-3-cryostat GPIB Bus now serving'
INFO:labrad.helium_level_meter:b"2020-09-20 21:28:04-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x1163E7D0>\r\n2020-09-20 21:28:04-0700 [-] COM5\r\n2020-09-20 21:28:04-0700 [-] ['COM4', 'COM5']"
INFO:labrad.dac_adc_24bits:b"2020-09-20 21:28:04-0700 [-] <labrad.wrappers.AsyncServerWrapper object at 0x12191690>\r\n2020-09-20 21:28:04-0700 [-] COM4\r\n2020-09-20 21:28:04-0700 [-] ['COM4', 'COM5']"
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:04-0700 [-] GPIB Device Connect: GPIB0::21::INSTR\r\n2020-09-20 21:28:04-0700 [-] GPIB Device Connect: TCPIP0::169.254.193.6::7180::SOCKET'
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:06-0700 [-] Failed to add TCPIP0::169.254.129.190::7180::SOCKET:VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.\r\n2020-09-20 21:28:06-0700 [-] GPIB Device Connect: GPIB0::8::INSTR'
INFO:labrad.he_3_cryostat_gpib_bus:b'2020-09-20 21:28:08-0700 [-] Failed to add TCPIP0::169.254.246.230::7180::SOCKET:VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.\r\n2020-09-20 21:28:08-0700 [-] GPIB Device Connect: GPIB0::1::INSTR'
INFO:labrad.lsci_model350:b'2020-09-20 21:28:08-0700 [-] Device message: LSCI MODEL350 he-3-cryostat GPIB Bus GPIB0::21::INSTR True'
INFO:labrad.gpib_device_manager:b"2020-09-20 21:28:08-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 21:28:08-0700 [-] Device Connect: he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 21:28:08-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 21:28:08-0700 [-] Device Connect: he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::21::INSTR\r\n2020-09-20 21:28:08-0700 [-] Error sending *IDN? to he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET: not enough values to unpack (expected 4, got 1)\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::8::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending *IDN? to he-3-cryostat GPIB Bus GPIB0::1::INSTR\r\n2020-09-20 21:28:08-0700 [-] Sending message: 11 (11, 0) [(21436587, ('LSCI MODEL350', 'he-3-cryostat GPIB Bus', 'GPIB0::21::INSTR', True))]\r\n2020-09-20 21:28:08-0700 [-] Sending message: 9 (9, 0) [(21436587, ('AMERICAN MAGNETICS INC. MODEL 430', 'he-3-cryostat GPIB Bus', 'TCPIP0::169.254.193.6::7180::SOCKET', True))]"
INFO:labrad.gpib_device_manager:b"2020-09-20 21:28:08-0700 [-] Sending message: 10 (10, 0) [(21436587, ('Stanford_Research_Systems SR830', 'he-3-cryostat GPIB Bus', 'GPIB0::8::INSTR', True))]"
INFO:labrad.gpib_device_manager:b"2020-09-20 21:28:08-0700 [-] Sending message: 10 (10, 0) [(21436587, ('Stanford_Research_Systems SR830', 'he-3-cryostat GPIB Bus', 'GPIB0::1::INSTR', True))]"
INFO:labrad.ami_430:b'2020-09-20 21:28:08-0700 [-] Device message: AMERICAN MAGNETICS INC. MODEL 430 he-3-cryostat GPIB Bus TCPIP0::169.254.193.6::7180::SOCKET True'
INFO:labrad.sr830:b'2020-09-20 21:28:08-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::8::INSTR True\r\n2020-09-20 21:28:08-0700 [-] Device message: Stanford_Research_Systems SR830 he-3-cryostat GPIB Bus GPIB0::1::INSTR True'
INFO:labrad.ami_430:b'2020-09-20 21:31:51-0700 [-] a'
INFO:labrad.ami_430:b'2020-09-20 21:32:09-0700 [-] a'
INFO:labrad.ami_430:b'2020-09-20 21:32:09-0700 [-] a'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 22:51:25-0700 [-] deferredRead timed out after 5.00080418586731 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 23:19:46-0700 [-] deferredRead timed out after 5.000657081604004 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-20 23:46:04-0700 [-] deferredRead timed out after 5.000890493392944 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 00:07:51-0700 [-] deferredRead timed out after 5.000655889511108 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 00:29:38-0700 [-] deferredRead timed out after 5.000672101974487 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 00:51:25-0700 [-] deferredRead timed out after 5.0006327629089355 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 01:13:12-0700 [-] deferredRead timed out after 5.000755786895752 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 01:35:00-0700 [-] deferredRead timed out after 5.000877141952515 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 01:56:46-0700 [-] deferredRead timed out after 5.0006186962127686 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 02:18:35-0700 [-] deferredRead timed out after 5.00058913230896 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 02:40:22-0700 [-] deferredRead timed out after 5.000874280929565 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 03:02:11-0700 [-] deferredRead timed out after 5.000800371170044 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 03:23:58-0700 [-] deferredRead timed out after 5.000866413116455 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 03:45:45-0700 [-] deferredRead timed out after 5.0005879402160645 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 04:07:32-0700 [-] deferredRead timed out after 5.000831842422485 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 04:29:20-0700 [-] deferredRead timed out after 5.000637531280518 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 04:51:07-0700 [-] deferredRead timed out after 5.000578880310059 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 05:12:54-0700 [-] deferredRead timed out after 5.000805616378784 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 05:34:42-0700 [-] deferredRead timed out after 5.000686407089233 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 10:46:01-0700 [-] deferredRead timed out after 5.000630140304565 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 11:25:56-0700 [-] deferredRead timed out after 5.000666618347168 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 11:54:34-0700 [-] deferredRead timed out after 5.0008580684661865 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 11:54:39-0700 [-] deferredRead timed out after 5.000665187835693 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 12:23:15-0700 [-] deferredRead timed out after 5.000812292098999 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 12:23:20-0700 [-] deferredRead timed out after 5.000713586807251 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 12:51:56-0700 [-] deferredRead timed out after 5.000606060028076 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 12:52:01-0700 [-] deferredRead timed out after 5.000805139541626 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 13:20:36-0700 [-] deferredRead timed out after 5.0007970333099365 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 13:20:41-0700 [-] deferredRead timed out after 5.000805854797363 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 13:49:17-0700 [-] deferredRead timed out after 5.0008673667907715 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 13:49:22-0700 [-] deferredRead timed out after 5.000847816467285 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 14:17:58-0700 [-] deferredRead timed out after 5.000699520111084 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 14:18:03-0700 [-] deferredRead timed out after 5.000568151473999 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 14:46:39-0700 [-] deferredRead timed out after 5.000632047653198 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 14:46:44-0700 [-] deferredRead timed out after 5.000604152679443 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 15:15:21-0700 [-] deferredRead timed out after 5.000861883163452 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 15:15:26-0700 [-] deferredRead timed out after 5.000803709030151 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 15:44:01-0700 [-] deferredRead timed out after 5.0006890296936035 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 15:44:06-0700 [-] deferredRead timed out after 5.0006186962127686 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:12:42-0700 [-] deferredRead timed out after 5.000908374786377 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:12:47-0700 [-] deferredRead timed out after 5.0006303787231445 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:46:06-0700 [-] deferredRead timed out after 5.000577449798584 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:46:11-0700 [-] deferredRead timed out after 5.000669479370117 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:58:21-0700 [-] deferredRead timed out after 5.000657081604004 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 16:58:26-0700 [-] deferredRead timed out after 5.000835418701172 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:01:34-0700 [-] deferredRead timed out after 5.000672101974487 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:01:39-0700 [-] deferredRead timed out after 5.000812530517578 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:21:33-0700 [-] deferredRead timed out after 5.000923156738281 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:21:38-0700 [-] deferredRead timed out after 5.000627517700195 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:28:26-0700 [-] deferredRead timed out after 5.000664472579956 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 18:28:31-0700 [-] deferredRead timed out after 5.0008790493011475 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 19:31:45-0700 [-] deferredRead timed out after 5.000872373580933 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 19:44:06-0700 [-] deferredRead timed out after 5.000857830047607 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 19:44:11-0700 [-] deferredRead timed out after 5.000856876373291 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 19:56:30-0700 [-] deferredRead timed out after 5.000619649887085 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 19:56:35-0700 [-] deferredRead timed out after 5.0006701946258545 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:08:54-0700 [-] deferredRead timed out after 5.000584363937378 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:08:59-0700 [-] deferredRead timed out after 5.000809907913208 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:21:18-0700 [-] deferredRead timed out after 5.000916242599487 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:21:23-0700 [-] deferredRead timed out after 5.000668525695801 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:33:41-0700 [-] deferredRead timed out after 5.000918388366699 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:33:46-0700 [-] deferredRead timed out after 5.000852584838867 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:46:04-0700 [-] deferredRead timed out after 5.000651836395264 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-21 20:46:09-0700 [-] deferredRead timed out after 5.0006139278411865 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-22 15:18:26-0700 [-] deferredRead timed out after 5.0006256103515625 seconds'
INFO:labrad.he_3_cryostat_serial_server:b'2020-09-22 15:18:31-0700 [-] deferredRead timed out after 5.000625848770142 seconds'
